name: Clang Format
on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.c'
      - '**/*.h'
      - '.github/workflows/*.yml'

permissions:
  contents: write
  actions: read

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format-14

    - name: Format files
      run: clang-format -i -style=file $(find src/ -name "*.c" -o -name "*.h") mate.h amalgam-script.c

    - name: Configure Git
      run: |
        git config --global user.name 'Mate Bot'
        git config --global user.email 'mate@yerba.ar'

    - name: Check for changes
      id: git-check
      run: |
        git status
        echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.git-check.outputs.changed != '0' && github.event_name == 'push'
      run: |
        git add .
        git commit -m "Format files via clang-format"
        git push
